name: plant_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.4
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  lottie: ^3.0.0

  # Image handling
  image_picker: ^0.8.6
  image_picker_android: ^0.8.12+12
  cached_network_image: ^3.3.1

  # Firebase
  firebase_core:
  firebase_auth: ^5.3.2
  cloud_firestore:
  firebase_storage:

  # State Management
  provider: ^6.1.2

  # Utilities
  intl: ^0.19.0
  http: ^0.13.6

  # Maps and Location
  flutter_svg: ^2.0.9
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0

  # Payment
  flutter_stripe: ^11.2.0
  flutter_google_places_sdk:
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_screenutil:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
